#!/usr/bin/env node
// Generate INDEX.md and personas.json from personas/*.md, and lint the schema.
// Nothing in the generated files is hand-maintained — the .md files are truth.
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const DIR = path.join(ROOT, 'personas');
const REQUIRED = ['The one trait', 'The question they ask', 'Blind spots'];

const files = fs.readdirSync(DIR).filter(f => f.endsWith('.md')).sort();
const out = [], problems = [];

for (const f of files) {
  const s = fs.readFileSync(path.join(DIR, f), 'utf8');
  const fm = (s.match(/^---\n([\s\S]*?)\n---/) || [])[1];
  if (!fm) { problems.push(`${f}: no frontmatter`); continue; }
  const get = k => ((fm.match(new RegExp(`^${k}:\\s*(.*)$`, 'm')) || [])[1] || '').trim();
  const list = k => { const v = get(k); return v.startsWith('[') ? v.slice(1, -1).split(',').map(x => x.trim()).filter(Boolean) : v ? [v] : []; };

  const name = get('name');
  const trait = (s.match(/## The one trait\n+([^\n]+)/) || [])[1] || '';
  const question = (s.match(/## The question they ask\n+\*\*(.+?)\*\*/s) || [])[1] || '';

  for (const sec of REQUIRED) if (!s.includes(`## ${sec}`)) problems.push(`${f}: missing "## ${sec}"`);
  if (!get('grounded_in') && !/grounded_in:\n\s+-/.test(fm)) problems.push(`${f}: no grounded_in — every persona must say where it came from`);
  // the one rule that matters: a quotes section that exists must not be empty
  if (/## Quotes\n+\s*##/.test(s)) problems.push(`${f}: empty Quotes section — omit it or fill it`);

  out.push({
    file: `personas/${f}`,
    name,
    also: list('also'),
    domains: list('domains'),
    era: get('era'),
    language: get('language'),
    verified: get('verified'),
    trait: trait.trim(),
    question: question.replace(/\n/g, ' ').trim(),
    hasMethod: s.includes('## Method'),
    hasQuotes: s.includes('## Quotes') && !/## Quotes\n+None included/.test(s),
  });
}

fs.writeFileSync(path.join(ROOT, 'personas.json'),
  JSON.stringify({ generated: new Date().toISOString(), count: out.length, personas: out }, null, 2) + '\n');

const rows = out.map(p => `| **${p.name}** | ${p.domains.join(', ')} | ${p.trait} | ${p.hasMethod ? '✓' : '—'} |`).join('\n');
fs.writeFileSync(path.join(ROOT, 'INDEX.md'),
`# Persona index

${out.length} personas. Generated by \`scripts/build.mjs\` — do not edit by hand.

| Persona | Domains | The one trait | Method |
|---|---|---|---|
${rows}

"Method ✓" means the file carries a runnable loop for \`/แปลงร่าง\`. Personas with
taste rather than a documented method are marked — that is not a gap to fill.
`);

for (const p of out) console.log(`  ${p.name.padEnd(26)} ${p.domains.join(', ').padEnd(34)} method:${p.hasMethod ? 'y' : 'n'}`);
console.log(`\n  ${out.length} personas → INDEX.md + personas.json`);
if (problems.length) { console.log('\n  PROBLEMS:'); problems.forEach(p => console.log('   ✗ ' + p)); process.exit(1); }
console.log('  ✓ schema clean');
